import mongoose from 'mongoose';
import { readFileSync } from 'fs';

const envContent = readFileSync('.env.local', 'utf8');
const envVars = Object.fromEntries(
  envContent.split('\n')
    .filter(line => line.includes('=') && !line.startsWith('#'))
    .map(line => { const [k, ...v] = line.split('='); return [k.trim(), v.join('=').trim()]; })
);
const MONGODB_URI = envVars.MONGODB_URI;

await mongoose.connect(MONGODB_URI);
const db = mongoose.connection.db;
const vendors = await db.collection('vendors').find({}).toArray();

const mdContent = `# Vendor Login Credentials

Here is the complete list of vendors generated by the system, along with their login credentials. All accounts use the same default password.

## Default Password
**Password**: \`password123\`

## Vendor Accounts

| Shop Name | Proprietor Name | Email Address |
|-----------|-----------------|---------------|
${vendors.map(v => `| ${v.shop_name} | ${v.full_name} | \`${v.email}\` |`).join('\n')}
`;

import { writeFileSync } from 'fs';
writeFileSync('vendor_credentials.md', mdContent);
console.log('✅ vendor_credentials.md created!');
process.exit(0);
